'\" t
.\"     Title: g7ctrl
.\"    Author: Johan Persson <johan162@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 03/02/2015
.\"    Manual: http://sourceforge.net/projects/g7ctrl/docs/
.\"    Source: http://sourceforge.net/projects/g7ctrl/ @VERSION@
.\"  Language: English
.\"
.TH "G7CTRL" "1" "03/02/2015" "http://sourceforge\&.net/proje" "http://sourceforge\&.net/proje"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
g7ctrl \- Control daemon for a GM7 GPS Tracker
.SH "SYNOPSIS"
.HP \w'\fBg7ctrl\fR\ 'u
\fBg7ctrl\fR [options\&.\&.\&.]
.SH "DESCRIPTION"
.PP
The
\fBg7ctrl\fR(1)
is a daemon that is used to manage a GM7 GPS tracker\&. The daemon has two main functions\&. One) it can receive incoming location messages on a specified TCP/IP port that the tracker sends and Two) It allows easy controlling of a GM7 tracker that is connected via USB to the server\&. Connecting the device with USB to the server is the easiest way to configure the tracker\&. The daemon defines a command set that is easier for the user compared with the native GM7 tracker protocol\&. It does not require the user to memorize all commands and their arguments but rather asks in clear text for what settings the user wants to change\&.
.PP
Even though it is perfectly possible to directly connect to the daemon on the specified command port it is recommended to use the supplied command shell
\fBg7sh\fR(1)\&. This will offer both full command line editing as well has history function\&. In addition it hides some of the extra protocol handling on the daemon to make it even more user friendly\&.
.PP
The configuration of the daemon such as what ports to listen on is controlled by the configuration file (by default this is found in
/etc/g7ctrl/g7ctrl\&.conf)\&.
.SH "ARGUMENTS"
.PP
The following command line arguments are supported when starting the daemon
.PP
\fI\-d, \-\-daemon [n|y]\fR
.RS 4
Determine whether the server should be disconnected from the controlling terminal (a\&.k\&.a\&. running as a daemon)\&. If the server is run as a daemon the logfile cannot be \*(Aq\fIstdout\fR\*(Aq\&. This command line option will override the \*(Aq\fIdaemon\fR\*(Aq setting in the configuration file\&. The default setting is to run as a daemon\&.
.RE
.PP
\fI\-h, \-\-help\fR
.RS 4
Print help
.RE
.PP
\fI\-i file, \-\-inifile=file\fR
.RS 4
Use the specified file as configuration file\&. This will override the location specified at compile time\&. The default location is \*(Aq/etc/g7ctrl/g7ctrl\&.conf\*(Aq
.RE
.PP
\fI\-l logfile, \-\-logfile=file\fR
.RS 4
Define the name of the logfile\&. Two special names can be used,
stdout
which will cause the log to be written to the
\fIstdout\fR
and
syslog
which will cause the logs to be written using the default system logger\&. This command line option will override the \*(Aq\fIlogfile\fR\*(Aq setting in the configuration file\&. The default location is \*(Aq/var/log/g7ctrl/g7ctrl\&.log\*(Aq
.RE
.PP
\fI\-p n, \-\-cmdport=n\fR
.RS 4
Specify what TCP/IP port number that the server will listening on for commands\&. This will override the \*(Aq\fIport\fR\*(Aq setting in the ini\-file\&. By default the command port is 3100\&.
.RE
.PP
\fI\-s n, \-\-stty=n\fR
.RS 4
Specify what
ttyACM<n>
device to use when connecting over USB to device
.RE
.PP
\fI\-t n, \-\-trkport=n\fR
.RS 4
Specify TCP/IP port number for receiving tracker updates\&. This will override the setting in the config file\&. Default port is 3400
.RE
.PP
\fI\-V n, \-\-verbose\fR
.RS 4
Log verbosity level\&. 0 will only log error messages, 1 will log error and info messages, 2 will log errors, info and additional notices finally 3 will also log (possibly) high volume debug messages\&.
.RE
.PP
\fI\-v, \-\-version\fR
.RS 4
Print version information and exit
.RE
.PP
\fI\-\-\-pidfile=file\fR
.RS 4
Specify PID lock file to be used\&. By default this is
/var/run/g7ctrl/g7ctrl\&.pid
so if the daemon is not started as root it must be specified since only root has access to
/var/run\&.
.RE
.PP
\fI\-\-\-datadir=directory\fR
.RS 4
Specify directory for static data files (default,is
/usr/share/g7ctrl) \&.
.RE
.PP
\fI\-\-\-dbdir=directory\fR
.RS 4
Specify directory for dynamic data files (default,is
/var/lib/g7ctrl) \&.
.RE
.PP
The default arguments corresponds to starting the server with
.PP
.if n \{\
.RS 4
.\}
.nf
g7ctrl \-i "/etc/g7ctrl/g7ctrl\&.conf" \-d Y \-s 0 \-p 3100 \-t 3400 \e
\-l "/var/log/g7ctrl/g7ctrl\&.log" V 2 \-\-pidfile="/var/run/g7ctrl/g7ctrl\&.pid" \e
\-\-dbdir="/var/lib/g7ctrl" \-\-datadir="/usr/share/g7ctrl"
.fi
.if n \{\
.RE
.\}
.sp
.SH "STARTING AND STOPPING THE SERVER"
.PP
While strictly speaking not necessary the server should normally be started by the
root
user\&. As soon as the server doesn\*(Aqt need
root
privileges it will switch to run as the user specified in the configuration file, by default this is the user
\fIg7ctrl\fR
if the configuration file has not been changed\&. This user should for security reasons not be the \*(Aqroot\*(Aq user\&. This user should be a system user without login shell\&. Such a user can normally be created by running the command \*(Aq\fIuseradd\fR\*(Aq\&. (If the daemon is installed via the RPM package this user will be automatically created)\&.
.PP
If your system supports the command
\fBuseradd\fR
then start by changing to root and add the user as so
.sp
.if n \{\
.RS 4
.\}
.nf
$> useradd \-r g7ctrl
.fi
.if n \{\
.RE
.\}
.PP
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
The user created must normally belong to the group
dialout
on most system in order to have access to the
USB\-serial device\&.
.sp .5v
.RE
.PP
Then to start the server as root using the settings in the configuration file the simplest way is to just call
.sp
.if n \{\
.RS 4
.\}
.nf
sudo g7ctrl
.fi
.if n \{\
.RE
.\}
.PP
In order to stop the server and allow it to do a clean shutdown the
SIGINT
(or
SIGSTOP) signal should be sent to the process running the server (assuming
\fBg7ctrl\fR
has been started as a daemon)\&. The distribution includes two support scripts to help with this\&. This can of course also be done manually as (and reading the pid number from the standard pid\-file)
.PP
.if n \{\
.RS 4
.\}
.nf
sudo kill \-SIGINT `cat /usr/share/g7ctrl/g7ctrl\&.pid`
.fi
.if n \{\
.RE
.\}
.PP
Please note the "`" backward slashes\&.
.PP
While testing the server it is also possible to start the daemon as a "normal" user\&. As a test start the daemon from command line for example as
.PP
.if n \{\
.RS 4
.\}
.nf
$g7ctrl \-dN \-V3 \-lstdout
.fi
.if n \{\
.RE
.\}
.PP
The commands will start the application on the terminal
\-dN
(not as a daemon), with maximum logging (\-V3) and print the log file directly to the terminal (\-lstdout)\&. This is a good way to do the initial testing since any problem can usually be quickly seen in the log\&. Note that when the daemon is not started as the root user it can not switch to the daemon user specified in the configuration file\&.
.PP
Once the testing is completed the daemon can be setup to be started at the same time as the server\&. Depending on the system this can done in a few different ways as the following two sections show\&.
.SS "For system using old style init\&.d"
.PP
To start the daemon automatically the installation will install two utility scripts\&. The first script will be installed in "/etc/init\&.d/g7ctrl" and follows the normal guidelines for a "init\&.d" service start/stopping script according to
LSB
(Linux Standard Base)\&. Using this script to start the server is then simply a matter of calling
.sp
.if n \{\
.RS 4
.\}
.nf
sudo /etc/init\&.d/g7ctrl start
.fi
.if n \{\
.RE
.\}
.PP
(or its alias
\fBrcg7ctrl\fR) is given\&. The start\-up script also supports the "restart" and "status" options\&.
.PP
If the server gives the error message : "\fIServer can not be started\&. See system log\fR" then more information about the details of the problem can be found in the system log, normally
/var/log/messages\&. The most common reason for this message is that the daemon is already running\&.
.PP
To stop the server give the command (as root)
.sp
.if n \{\
.RS 4
.\}
.nf
sudo /etc/init\&.d/g7ctrl stop
.fi
.if n \{\
.RE
.\}
.PP
Since the
init\&.d
system has been abandoned in most modern system the
init\&.d
scripts will then be automatically redirected to the corresponding
systemd
service\&. In that case it is better to just use the
systemd
service directly as the following section shows\&.
.SS "Using systemd"
.PP
If your system makes use of
systemd
then the second utility script will be installed as a
systemd
service\&. The configuration script will automatically figure out if your system supports this\&. In this case the daemon can be directly controlled via the usual
\fBsystemctl\fR
command as shown below\&. See
\fBman systemctl\fR
for details\&.
.PP
.if n \{\
.RS 4
.\}
.nf
sudo systemctl stop g7ctrl\&.service
.fi
.if n \{\
.RE
.\}
.PP
.if n \{\
.RS 4
.\}
.nf
sudo systemctl start g7ctrl\&.service
.fi
.if n \{\
.RE
.\}
.PP
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
The
g7ctrl
service needs to first be enabled after the initial installation with
.PP
.if n \{\
.RS 4
.\}
.nf
sudo systemctl enable g7ctrl\&.service
.fi
.if n \{\
.RE
.\}
.sp .5v
.RE
.PP
If your system does not have the command
\fBsystemctl\fR
then it is not using the
systemd
setup\&.
.SS "Using upstart"
.PP
Newer version of Debian and Ubuntu now uses "upstart" to manage daemons\&. The build system fylly supports this and after the usual "\fBsudo make install\fR" the daemon could be controlled by
.PP
.if n \{\
.RS 4
.\}
.nf
sudo start g7ctrl
sudo stop g7ctrl
sudo status g7ctrl
.fi
.if n \{\
.RE
.\}
.PP
or alternatively by
.PP
.if n \{\
.RS 4
.\}
.nf
sudo service g7ctrl start
sudo service g7ctrl stop
sudo service g7ctrl status
.fi
.if n \{\
.RE
.\}
.PP
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
.PP
The configuration file for upstart is stored in
/etc/init/g7ctrl\&.conf
.sp .5v
.RE
.SH "INTERFACING WITH THE SERVER"
.PP
The primary interface to the server is via a TCP/IP connection to the server running \*(Aq\fIg7ctrl\fR\*(Aq via a dedicated port (by default 3100)\&. The server is controlled via a simple (but efficient) command language which allows manipulation of future recordings and various other administrative tasks\&. All commands are extensively described in the section \*(AqCommand language\*(Aq below\&.
.PP
The preferred way of interacting with the server on the command level is by using the supplied utility shell \*(Aqg7sh\*(Aq\&. This supports history and full command line editing and is recommended over a plain \*(Aqtelnet\*(Aq (nc
command)or connections to the server\&.
.PP
See the section "Connecting to the server" below for more detailed examples\&.
.SH "CONNECTING DIRECTLY TO THE SERVER"
.PP
By default the best way to communicate with the daemon is to us the
\fBg7sh\fR
command, see below\&. But the following information may be used for additional troubleshooting\&.
.PP
We start by describing the direct method that communicates with the daemon directly on the command port\&. This is for illustrative purpose only and can be a quick way to check that the daemon is really running when troubleshooting\&. For normal usage it is recommended to use the
\fBg7sh\fR(1)
utility shell program (seel also next section)\&.
.PP
Once the server is running the easiest way to connect to the command is by using the \*(Aq\fInc\fR\*(Aq (\*(Aqnet cat) program\&. Assuming that the
\fIg7ctrl\fR
server is running on the localhost the following command will connect to the server (assuming the default port 3100 has not been changed (either in the configuration file (e\&.g\&.
/etc/g7ctrl\&.conf) or by a command line argument)\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$> nc localhost 3100
.fi
.if n \{\
.RE
.\}
.PP
After a successful connection the server will reply with a short, one line, information message\&. The full returned information message at the connection time should look something similar to the following (the version and build might be different though):
.sp
.if n \{\
.RS 4
.\}
.nf
GM7 Server version 3\&.0\&.0 (build 150108\-110)
.fi
.if n \{\
.RE
.\}
.PP
If password protection (see section "Security" below) the welcome message is not be shown until the correct password has been specified\&. Instead when password protection is enabled the connection sequence looks like this
.sp
.if n \{\
.RS 4
.\}
.nf
$> nc localhost 3100
Password:\fBxxxxxxx\fR
GM7 Server version 3\&.0\&.0 (build 150108\-110)
.fi
.if n \{\
.RE
.\}
.PP
This means that the correct server password has to be given before the welcome message is seen\&. The server is now ready to accept commands on this connection\&.
.PP
To disconnect to the server give the command \*(Aq\fBexit\fR\*(Aq
.SH "USING THE G7SH TO CONNECT TO THE DAEMON"
.PP
The package also includes a full command line shell,
\fBg7sh\fR\&. This allows much better editing (Emacs compatible editing) as well as full command line history\&. This shell can also be used as a system login shell and hereby making it possible to connect to the daemon using
\fBssh\fR
for a more secure communication by creating a unique user with g7sh as the login shell\&.
.PP
How to setup and use the g7sh command line shell is fully described in
\fBg7sh\fR(1)
.PP
In its simplest form (assuming it is the same sever as the daemon) the shell can be started with
.PP
.if n \{\
.RS 4
.\}
.nf
$ g7sh
.fi
.if n \{\
.RE
.\}
.PP
Run
\fBg7sh \-h\fR
for a list of supported options\&.
.SH "DIRECTORY STRUCTURE"
.PP
The daemon uses two distinct directories on the server; one data directory where the database and log files are stored and one configuration directory\&. The default location of these directories are specified at build but may be overridden by either the configuration file or by command line arguments\&. The package default locations are shown below
.PP
.PP
/etc/g7ctrl
.RS 4
Configurations file\&.
.RE
.PP
/usr/share/g7ctrl
.RS 4
This is the data directory where static data files (like mail templates and presets) are stored\&.
.RE
.PP
/var/lib/g7ctrl
.RS 4
This is the data directory where dynamic data files (like DB) are stored\&.
.RE
.SH "SECURITY"
.PP
In order to prevent unauthorized access to the server the server have a basic password protection\&. This means that a password can be configured to be used before a client can start giving command to the server\&. This is configured in the ini\-file\&. The configuration uses the same password for all clients so the server does not support multiple users/multiple password\&. Since the password is stored in plain text format the configuration file should have restricted access\&. This should not be considered strong security but rather a weak "stop\-messing\-with\-daemon" type of protection\&.
.PP
Sine the password are sent unencrypted to the daemon it is also susceptible to line snooping\&.
.PP
The setting whether password should be used or not and the actual password is specified in the ini\-file\&.
.PP
After connecting to the server when the password has been enabled the first string sent back from the server will be the single string:
.sp
.if n \{\
.RS 4
.\}
.nf
Password:
.fi
.if n \{\
.RE
.\}
.PP
The rest of the reply is the same as when no password is used\&.
.PP
If security is of concern the daemon can also be configured to only allow connections from the localhost, i\&.e\&. connections must be made from the same machine that is running the daemon\&. This is done by enabling the option "only_localhost" in the config file\&.
.SH "MANAGING NOTIFICATIONS MAILS"
.PP
When configuring the daemon it is possible to set options that will send notification mails on important events in the daemon\&. This could be notifications on errors that occurred but also notifications on that a transcoding was finished or that the server was shutdown automatically while waiting for the next recording\&.
.PP
All mail settings are specified in the "[mail]" section of the configuration file\&. More information is available in the full application manual\&.
.SH "COMMANDS (IN ALPHABETIC ORDER)"
.PP
The following is a list and detailed explanation of the commands that are recognized by the server\&.
.PP
Since there are quite a few commands we start with an overview with a one line explanation of each command\&. Further details can be found below
.PP
There commands are divided into three different areas
.PP
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Device commands\&. They are commands that controls a connected device
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Database commands\&. Commands to export and read the database
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Preset commands\&. Commands to manipulate presets
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Daemon commands\&. Commands to act on the daemon itself\&.
.RE
.sp
.SS "Device Command reference"
.PP
Below is the commands possible together with there parameters\&. In case a command can accept argument the daemon will ask for each command in sequence\&. The prompt will always be indicated by a "?" mark\&. To abort a specific command just type a single dot "\&." and the command shell will return to the start position (outer level)\&. Most commands only accept a selected value chosen from a list\&. All possible values in the lists are shown below\&.
.PP
For even more detailed command information please refer to the "\fIGM7 Protocol specification\fR" available from where you purchased your device\&.
.PP
\fBaddress\fR
.RS 4
Return the current location as an approximate street address
.RE
.PP
\fBclrec\fR
.RS 4
Erase all recorded locations in device memory\&. Use
dlrec
to read back the recorded location positions in device memory to the database\&.
.RE
.PP
\fBcomm\fR
.RS 4
Set/Read device communication type and its parameters
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fICommSelect\fR
\- Select primary type of communication
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Use USB"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Use SMS over GSM"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "CSD (reserved)"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "UDP over GPRS"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI4\fR
\- "TCP/IP over GPRS"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fISMS Base Phone\fR
\- SMS base number to call
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fICSD Base Phone\fR
\- CSD base number (reserved and not used)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGPRS APN\fR
\- The operators APN
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGPRS User\fR
\- User name if required
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGPRS Passwd\fR
\- Password if required
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGPRS Server\fR
\- Server IP address where the device reports back to
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGPRS Server Port\fR
\- TCP/IP Port to use on server
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGPRS Keep Alive\fR
\- Interval (in sec) between Keep Alive Packets
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIGPRS DNS\fR
\- Optional DNS server for device to use\&.
.RE
.sp
.RE
.PP
\fBconfig\fR
.RS 4
Set/Read device ID, Password, and PIN Code of the SIM card
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIDevice ID\fR
\- Set device ID (leftmost digit must always be 3)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIDevice Password\fR
\- Set device Password (numeric)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fISIM Card PIN\fR
\- The SIM cards PIN code to use
.RE
.sp
.RE
.PP
\fBdlrec\fR
.RS 4
Download all recorded position in device memory to the database\&. Positions that have been downloaded from the device memory in this way will have an event id of
1\&.
.sp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
Please note that download and DB update takes a bit of time\&. As an example download and DB updated of 10,000 locations took 17s in one instance\&. The bulk of the time, ~95%, is spent downloading the data from the device over the serial line and ~5% was spent to update the DB with the new locations\&.
.sp .5v
.RE
.RE
.PP
\fBgeofevt\fR
.RS 4
Enable/Disable/Set/Read GEO\-Fencing event
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIEvent ID\fR
\- Event ID\&. Maximum of 50 events\&. In range 50\-99
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIEnabled\fR
\- Enable/Disable event
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fILongitude\fR
\- Longitude for center of event zone
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fILatitude\fR
\- Latitude for center of event zone
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIRadius\fR
\- Radius of event zone in meters (0\-65535)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIZoneControl\fR
\- How to trigger event
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Entering zone"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Leaving zone"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIAction\fR
\- What to do on event
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Log to device"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Send to server"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "Both log and send"
.RE
.RE
.sp
.RE
.PP
\fBgfen\fR
.RS 4
Enable/Disabling GEO\-fencing functionality
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIEnabled\fR
\- Turn option on/off
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIRadius\fR
\- Radius in meter for fence
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIZone trigger\fR
\- Trigger when leaving or entering zone
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Inside zone"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Outside zone"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIReport action\fR
\- What to do on event
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Disabled"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Log to device"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Send to server"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "Both log and send"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP mask\fR
\- Bitmask of VIP numbers to alert
.RE
.sp
.RE
.PP
\fBimei\fR
.RS 4
Query the IMEI number of the internal GSM module
.RE
.PP
\fBled\fR
.RS 4
Enable/Disable the LED indicator on/off
.RE
.PP
\fBloc\fR
.RS 4
Get latest location
.RE
.PP
\fBlocg\fR
.RS 4
Get the latest position as a Google map link
.RE
.PP
\fBlowbatt\fR
.RS 4
Set/Read the internal battery low level alert
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIReport action\fR
\- Action to perform at low battery voltage
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Disable"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Log on device"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Send back to server"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "Both log and send back ro server"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP mask\fR
\- Bit\-mask of VIP numbers to alert
.RE
.sp
.RE
.PP
\fBmswitch\fR
.RS 4
Enable/Disable detached report
.RE
.PP
\fBnrec\fR
.RS 4
Return date range and number of location records stored in device memory
.RE
.PP
\fBphone\fR
.RS 4
Enable the function "Get the current location by making a phone call"
.RE
.PP
\fBps\fR
.RS 4
Enable/Disable power saving mode
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIMode\fR
\- Select when to enable sleep mode to save battery
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Sleep after 3min of no movement\&. Wake up on movements\&. GSM=Standby, GPRS=GPS=Off, G\-sensor=On"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Always enter sleep after 3min and wake every n seconds specified\&. GSM=GPRS=GPS=G\-sensor=Off"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Always enter sleep after 3min and wake up on timer\&. GSM=GPRS=GPS=G\-sensor=Off"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "Always enter sleep after 3min and wake up on movement\&. GSM=GPRS=GPS=Off, G\-sensor=On"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fISleep interval\fR
\- Used with sleep mode 1, Interval in minutes between wake\-ups
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIWake up report\fR
\- Action when awaken
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Disable"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Log on device"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Send back to server"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "Both log and send back ro server"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP mask\fR
\- Bit\-mask of VIP numbers to alert on awake
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fITimer 1\fR
\- Used with mode=2\&. 00\-23 hr
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fITimer 2\fR
\- Used with mode=2\&. 00\-23 hr
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fITimer 3\fR
\- Used with mode=2\&. 00\-23 hr
.RE
.sp
.RE
.PP
\fBreboot\fR
.RS 4
Restart\-up the device
.RE
.PP
\fBrec\fR
.RS 4
Enable/Disable/read logging function to the device
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIMode\fR
\- When should logging be done
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Disable"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Time mode, log every n seconds"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Distance mode, log every n meters"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "Time AND Distance mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI4\fR
\- "Time OR Distance mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI5\fR
\- "Heading mode, logging starts when heading > set value"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI6\fR
\- "Heading OR Time mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI7\fR
\- "Heading OR Distance"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI8\fR
\- "Heading OR (Time AND Distance)"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI9\fR
\- "Heading OR Time OR Distance"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fITime interval\fR
\- Time interval (in sec) used in mode setting
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIDistance interval\fR
\- Distance interval (in meters) used in mode setting
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fINumber of reports\fR
\- The number of reports to send back on event (0=continuous logging)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIRecord basis\fR
\- Logging mode
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Wait for GPS fix before sending back report"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Don\*(Aqt wait for GPS fix before sending back report"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIHeading\fR
\- Heading value used in mode (10\-90)
.RE
.sp
.RE
.PP
\fBreset\fR
.RS 4
Reset all parameters to the manufacture default settings
.RE
.PP
\fBroam\fR
.RS 4
Enable/Disable GPRS roaming function
.RE
.PP
\fBsim\fR
.RS 4
Query the identification of the SIM card
.RE
.PP
\fBsleep\fR
.RS 4
Enable/Disable "Sleeping Report"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIMessage mode\fR
\- Set how to handle message at when device enters sleep
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "log message to device"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "send back message"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "both log and send back message"
.RE
.RE
.sp
.RE
.PP
\fBsms\fR
.RS 4
Switch the SMS format (Text of PDU mode)
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIMode\fR
\- Set format for SMS sent back
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Use PDU mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Use text mode"
.RE
.RE
.sp
.RE
.PP
\fBstopdl\fR
.RS 4
Stop downloading logging data from the device
.RE
.PP
\fBtest\fR
.RS 4
Device diagnostic function
.RE
.PP
\fBtrack\fR
.RS 4
Control if device should be sending back automatic tracking information\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fITracking mode\fR
\- Set condition for when tracking is started
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Time mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Distance mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "Time AND Distance mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI4\fR
\- "Time OR distance"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI5\fR
\- "Heading mode"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI6\fR
\- "Heading OR time"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI7\fR
\- "Heading OR distance"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI8\fR
\- "Heading OR (Time AND Distance"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI9\fR
\- "Heading OR Time OR Distance"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fITimer interval\fR
\- Used for mode 1
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIDistance interval\fR
\- Used for mode 2\-9
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fINumber of tracking\fR
\- Use 0 for continuous tracking
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fITrack basis\fR
\- Wait for GPS fix or not
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Send report ONLY if GPS is fixed"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Send report regardless of GPS status"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIComm select\fR
\- Set type of report
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "Over USB"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI1\fR
\- "Over GSM"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI2\fR
\- "Over Reserved (not used)"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI3\fR
\- "UDP over GPRS"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI4\fR
\- "TCP/IP over GPRS"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIHeading\fR
\- Used for modes 5\-9
.RE
.sp
.RE
.PP
\fBtz\fR
.RS 4
Set the time zone information for the device
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fISign\fR
\- Ahead or before GMT zone
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI+\fR
\- "Ahead of GMT"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI\-\fR
\- "Before GMT"
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIHour\fR
\- Number of hours to adjust (0\-9)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIMin\fR
\- Minutes to adjust
.sp
Possible values and description:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI0\fR
\- "0 min"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI15\fR
\- "15 min"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI30\fR
\- "30 min"
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fI45\fR
\- "45 min"
.RE
.RE
.sp
.RE
.PP
\fBver\fR
.RS 4
Get current firmware version
.RE
.PP
\fBvip\fR
.RS 4
Preset up to 5 SMS phone numbers for receiving different alerts
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP 1\fR
\- Mobile number 1 (full number incl country prefix \*(Aq+\*(Aq if needed)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP 2\fR
\- Mobile number 2 (full number incl country prefix \*(Aq+\*(Aq if needed)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP 3\fR
\- Mobile number 3 (full number incl country prefix \*(Aq+\*(Aq if needed)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP 4\fR
\- Mobile number 4 (full number incl country prefix \*(Aq+\*(Aq if needed)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIVIP 5\fR
\- Mobile number 5 (full number incl country prefix \*(Aq+\*(Aq if needed)
.RE
.sp
.RE
.SS "Database commands"
.PP
The database commands are used to manage the stored location updates from the devices\&.
.PP
db dist [dev=nnn] [ev=nnn] [from to]
.RS 4
Calculate the
\fB\fIapproximate distance\fR\fR
traveled using the selected data set of location points\&.
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[dev=nnn]
\- Filter on a specific device\-id\&. If not set all devices will be considered\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[ev=nnn]
\- Filter on specific event\&. If not set all events will be considered\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[from to]
\- Filter on a specific date range\&. Dates are given in
YYYY\-MM\-DD
format with optional time specification as
HH:MM
in 24h format (military time)\&. If omitted all dates are considered\&.
.RE
.sp
Calculation of distance is approximation of the distance between two
GPS
points (assuming WGS\-84 projection) and returns the result using both the
\fIHaversine\fR
method (great circle distance) and
\fIVincenty\fR
method (iterative)\&. The reply from the daemon is given as two lines exemplified by
.sp
.if n \{\
.RS 4
.\}
.nf
Calculating approximate distance using 344 points\&.
25\&.3 km (alt\&. 25399\&.5 m)
.fi
.if n \{\
.RE
.\}
.sp
The second distance in
m
are calculated using the
\fIVincenty\fR
method and the first distance (in
km) is calculated using the
\fIHaversine\fR
method\&.
.sp
Due to the number of error sources in getting location updates and limitations inherent in this type of distance calculations
\fBwe can not in general assume to have perfect accuracy\fR\&. The accuracy will also vary depending on the absolute location due to differences in the earth radius\&. The way traveled between recorded positions is assumed to follow the great circle between the points so the more points the better approximation of the actual real distance\&.
.sp
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
The precise volatility in the distance figures are very difficult to quantify due to the large number of factors that influence the
GPS
signal and the way the distance can be calculated\&. However,practical tests (with the GM7 device) have shown that in general it is safe to assume that the true distance (as measured in the middle part of Sweden around lat 57\(de) in more than 80% of the cases have less than 5% error compared with the distance as measured by an odometer\&. If more accuracy is needed in a particular area then field tests with known distances needs to be performed and correction factors introduced\&.
.sp
Often the distance is slightly underestimated and the longer time interval between each measure the more the distance is underestimated\&. This is due to the fact that the distance travelled between each measured point is assumed to be the shortest (great circle) distance and in practice the real distance is always longer\&.
.sp
(The
\fIVincenity\fR
method will generally have better accuracy assuming perfect
GPS
positions\&. )
.sp .5v
.RE
.sp
\fB Examples: \fR
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
db dist
.sp
Use all the data points and calculate the total traveled distance
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
db dist ev=1 2013\-08\-01 2013\-08\-01
.sp
Calculate the traveled distance from the previously imported data points from the internal memory of the device (they will have eventid=1) for the 1:st of August 2013\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
db dist 2013\-01\-01 2013\-12\-31 13:00
.sp
Calculate the total distance in DB for 2013 regardless of what event triggered the location update
.RE
.sp
.RE
.PP
db export [dev=nnn] [ev=nnn] [from to] (gpx|kml|xml|csv|json) [filename]
.RS 4
Exports the database in the selected format
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[dev=nnn]
\- Filter on a specific device id\&. If not set all devices will be considered\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[ev=nnn]
\- Filter on specific event\&. If not set all events will be considered\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[from to]
\- Filter on a specific date range\&. Dates are given in YYYY\-MM\-DD format\&. If omitted all dates are considered\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
(gpx|kml|xml|csv|json)
\- Export format to use
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
[filename]
\- Full filename path to export to\&. If omitted the data will be exported to
/var/lib/g7ctrl/export\&.<format>
.RE
.sp
\fB Examples: \fR
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
db export gpx
.sp
Export all stored location in GPX format to
/var/lib/g7ctrl/export\&.gpx
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
db export dev=3000000001 2013\-02\-01 2013\-02\-28 xml /tmp/myexport\&.xml
.sp
Export all location reported in February for device
3000000001
in g7ctgrl own
XML
format to the file
/tmp/myexport\&.xml
.RE
.sp
.RE
.PP
db lastloc
.RS 4
Display the latest recorded position
.RE
.PP
db mailpos
.RS 4
Mail the last recorded position
.RE
.PP
db mailgpx
.RS 4
Mail a compressed version of a GPX export of the entire DB to the predefined mail address\&.
.RE
.PP
db mailcsv
.RS 4
Mail a compressed version of a CSV export of the entire DB to the predefined mail address\&.
.RE
.SS "Preset commands"
.PP
The preset commands are used to manage the stored commands in the presets
.PP
preset list
.RS 4
List all define presets
.RE
.PP
preset refresh
.RS 4
Re\-read all presets from disk
.RE
.PP
preset use <preset\-name>
.RS 4
Execute the specified preset\&. A shortcut for this is "@<preset\-name>"
.RE
.PP
preset help <preset\-name>
.RS 4
Print help for the specified preset
.RE
.SS "Daemon commands"
.PP
Daemon commands are internal commands to work with the daemon itself\&.
.PP
\&.ver
.RS 4
Display the version of the daemon
.RE
.PP
\&.dev
.RS 4
Show if the device is connected or not
.RE
.PP
\&.lc
.RS 4
List active command connections
.RE
.PP
\&.ld
.RS 4
List all connected devices, both over GPRS and on USB
.RE
.PP
\&.target <dev>
.RS 4
List or set device connected over GPRS to receive commands
.RE
.PP
\&.usb <dev>
.RS 4
List or set device connected on USB to receive commands
.RE
.PP
\&.nick
.RS 4
Specify a new nick name for device
.RE
.PP
\&.ln
.RS 4
List all defined nick names
.RE
.PP
\&.dn
.RS 4
Delete the specified nick
.RE
.SH "FILES"
.PP
Note: The system configuration directory to be used is a compile time settings and specified with the \*(Aq\fIconfiguration\fR\*(Aq argument \*(Aq\-\-sysconfdir\*(Aq\&.
.PP
/var/log/g7ctrl/g7ctrl\&.log
.RS 4
The logfile\&. The log\-directory is specified in the ini\-file\&. It can also be specified as a command line argument (\fB\-l, \-\-logfile\fR) which will then override any config file setting\&. By default the log file will be stored under
/var/log/g7ctrl/g7ctrl\&.log\&.
.RE
.PP
/var/run/g7ctrl/g7ctrl\&.pid
.RS 4
The pid of the started \*(Aqg7ctrl\*(Aq server\&. This is used to easily find the pid in order to shutdown the server\&. This is used by the
\fIstop\-g7ctrl\fR
script\&. Note that in order to use this directory the daemon has to be started by the root user\&.
.RE
.PP
/etc/g7ctrl/g7ctrl\&.conf
.RS 4
Default configuration file
.RE
.PP
/var/lib/g7ctrl/gm7tracker_db\&.sqlite3
.RS 4
The sqlite3 database where all locations are stored\&.\&.
.RE
.SH "LIMITATIONS"
.PP
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
All information, error messages and loggings are hard coded in English\&.
.RE
.sp
.SH "BUGS"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
The configuration file has too many settings\&.
.RE
.SH "NOTES"
.PP
Any errors that are discovered in the start\-up phase before a logfile has been established will be written to the default system log (normally
/var/log/messages
or
/var/log/syslog)
.SH "RESOURCES"
.PP
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
SourceForge: <http://sourceforge\&.net/projects/g7ctrl/>
.RE
.sp
.SH "AUTHOR"
.PP
Written and maintained by Johan Persson <<johan162@gmail\&.com>>
.SH "COPYRIGHT"
.PP
Free use of this software is granted under the terms of the
GNU
General Public License (GPL v3), see the file
COPYING
included in the distribution archive for details\&.
.SH "SEE ALSO"
.PP
\fBg7sh\fR(1)
.SH "AUTHOR"
.PP
\fBJohan Persson\fR <\&johan162@gmail\&.com\&>
.RS 4
Main author and maintainer
.RE
